### PR TITLE
Features

### PR DESCRIPTION
**Pull request by flov3rh**

### CODE REVIEW

**Review by Torres-ssf — CHANGES_REQUESTED** [review]
### Hi there team :hand: 
Nice work on implementing the responsive behavior in this page :+1: 
But it's missing some needed features.

[REQUIRED]
- [ ] I notice that you are not using the linter. Linting is important to reduce errors and improve the overall quality of your code. Using the linter also gives a professional look in your repository :smiley: . Please look at the instruction in the pathwrite and set up the linter. You will also need to fix any errors that it may find. 

[REQUIRED]
- [ ] I notice that you didn't actually clone the page. The purpose of this assignment it's to learn more about how to build a proper responsive page. So in order to approved, you will need to actually clone the page. Working with headings and paragraphs it's also tricky, and that's will improve your knowledge. You don't need to use the same images from the original page, but everything else is needed. Each section should look the same in all 3 breakpoints (small: max-width around 700, medium: max-width around 1000, large: width over 1000).

[REQUIRED]

- [ ] I notice that there some broken links in your readme file. Let's fix this.

[OPTIONAL]

- [ ] Nice job using the section tag. But you could also make every single article to be an `article` tag. This will improve the semantic HTML from your code.

Please kindly make these changes and submit for code review again.
Happy coding :computer:

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Hi Team, you are making steady progress :+1: 
### But the changes requested by has been implemented:
- [ ] There are no stickler checks on this project
- [ ] In your README file, the images are still broken; kindly fix it.
- [ ] Your Html files is failing the validation test, kindly fix it.

### Kindly implement these changes and submit another form for code review. :smiley: 

### Cheers Henry!

**Review by stratospherique — CHANGES_REQUESTED** [review]
#### Great work so far :clap: . Almost done. 
### But you still have some linting errors, kindly fix it and submit another code review request :pray: :pray:

**Comment by flov3rh** [comment]
> t you still have some linting errors, kindly fix it an
the are all warnings
image

**Comment by esmoradian** [comment]
so we set up the stickler and we got 859 errors, which all seem trivial like space after colon etc., im not about to correct 859 errors, so if there are some settings we can use that can help ignore trivial issues or ignore the stickler in general that would be great. We've already put in an incredible amount of time...

**Review by stratospherique — APPROVED** [review]
### Great work :clap: . Linter errors fixed :100: . You shall merge to master :+1: :+1: . Your project is approved :heavy_check_mark:

**Pull request merged**
